# Generated by Django 3.2.7 on 2021-09-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210922_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='categoria_tema',
            field=models.CharField(choices=[('instmsc', 'Instrumento musical'), ('tmsc', 'Teoría musical'), ('prgm', 'Programación'), ('dbj', 'Dibujo'), ('art', 'Artesanías'), ('mnga', 'Manga - Anime'), ('ltr', 'Literatura'), ('coci', 'Cocina'), ('mrk', 'Marketing'), ('dsgn', 'Diseño'), ('otrs', 'Otros')], max_length=32),
        ),
    ]
