# Generated by Django 3.2.7 on 2021-09-24 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tema_categoria_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='imagen_tema',
            field=models.ImageField(upload_to='themes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
