# Generated by Django 3.2.7 on 2021-10-02 21:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20210930_1414"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fecha_nacimiento",
            field=models.DateField(default=datetime.date(2021, 10, 2)),
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        max_length=255, verbose_name="Titulo del tutorial"
                    ),
                ),
                ("banner", models.ImageField(upload_to="tutorials")),
                (
                    "descripcion",
                    models.CharField(
                        max_length=255, verbose_name="Descripción del tutorial"
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("bas", "Básico"),
                            ("med", "Intermedio"),
                            ("adv", "Avanzado"),
                        ],
                        max_length=32,
                        verbose_name="Dificultad del tutorial",
                    ),
                ),
                ("sensible", models.BooleanField(default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_Usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tutorial",
                "verbose_name_plural": "Tutoriales",
            },
        ),
    ]
