# Generated by Django 3.2.7 on 2021-10-03 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_pluma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fecha_nacimiento",
            field=models.DateField(default=datetime.date(2021, 10, 3)),
        ),
        migrations.CreateModel(
            name="TemaTutorial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tematutorial_Tema",
                        to="api.tema",
                    ),
                ),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tematutorial_Tutorial",
                        to="api.tutorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tema del tutorial",
                "verbose_name_plural": "Temas del tutorial",
            },
        ),
    ]
