# Generated by Django 3.2.7 on 2021-10-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_auto_20211003_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="descripcion",
            field=models.CharField(
                help_text="Un texto corto que indique la intención de tu tutorial",
                max_length=255,
                verbose_name="Descripción del tutorial",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="sensible",
            field=models.BooleanField(
                default=False, help_text="Es tu tutorial apto para todos?"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Correo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="facebookurl",
            field=models.URLField(
                blank=True, null=True, verbose_name="Enlace a Facebook"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="instagramurl",
            field=models.URLField(
                blank=True, null=True, verbose_name="Enlace a Instagram"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="twitterurl",
            field=models.URLField(
                blank=True, null=True, verbose_name="Enlace a Twitter"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="youtubeurl",
            field=models.URLField(
                blank=True, null=True, verbose_name="Enlace a Youtube"
            ),
        ),
        migrations.CreateModel(
            name="Paso",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paso", models.IntegerField(verbose_name="Número de paso")),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        upload_to="steps",
                        verbose_name="Imagen de referencia (No es obligatoria)",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Escribe tanto como sea necesario para expresar tu idea",
                        verbose_name="Descripción del paso",
                    ),
                ),
                (
                    "adjunto",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de referencia"
                    ),
                ),
                (
                    "tutorialpadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paso_Tutorial",
                        to="api.tutorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paso",
                "verbose_name_plural": "Pasos",
            },
        ),
    ]
