# Generated by Django 3.2.7 on 2021-10-03 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_auto_20211003_1515"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_comentario", models.DateField(auto_now=True)),
                (
                    "texto_comentario",
                    models.TextField(
                        help_text="Qué tal te ha parecido éste tutorial?",
                        verbose_name="Comentario",
                    ),
                ),
                (
                    "comentador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentario_Usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutorialpadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentario_Tutorial",
                        to="api.tutorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
            },
        ),
    ]
