# Generated by Django 3.2.7 on 2021-10-03 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_comentario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_respuesta", models.DateField(auto_now=True)),
                (
                    "texto_respuesta",
                    models.TextField(
                        help_text="Algo que decir de éste comentario?",
                        verbose_name="Respuesta",
                    ),
                ),
                (
                    "comentadorrespuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuesta_Usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comentariopadre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuesta_Comentario",
                        to="api.comentario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
            },
        ),
    ]
