# Generated by Django 3.2.7 on 2021-10-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_respuesta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comentario",
            old_name="tutorialpadre",
            new_name="tutorial_padre",
        ),
        migrations.RenameField(
            model_name="paso",
            old_name="tutorialpadre",
            new_name="tutorial_padre",
        ),
        migrations.RenameField(
            model_name="respuesta",
            old_name="comentadorrespuesta",
            new_name="comentador_respuesta",
        ),
        migrations.RenameField(
            model_name="respuesta",
            old_name="comentariopadre",
            new_name="comentario_padre",
        ),
    ]
