# Generated by Django 3.2.7 on 2021-10-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/6/6e/Breezeicons-actions-22-im-user.svg', null=True, upload_to='users'),
        ),
    ]
