# Generated by Django 3.2.7 on 2021-10-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_user_foto_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="foto_perfil",
            field=models.ImageField(
                blank=True, default="shorturl.at/gkxT5", null=True, upload_to="users"
            ),
        ),
    ]
