# Generated by Django 3.2.7 on 2021-11-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_alter_user_foto_perfil"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pluma",
        ),
    ]
