# Generated by Django 3.2.7 on 2021-11-10 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_delete_pluma"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="plumas_comentarios",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="plumas_tutoriales",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
