# Generated by Django 3.2.7 on 2021-11-14 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_comunicado"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicado",
            name="plumas_comunicados",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
