# Generated by Django 3.2.7 on 2021-11-24 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_comunicado_contenido"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacionCreacionTutorial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_notificacion", models.DateTimeField(auto_now=True)),
                (
                    "tutorial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tutorial"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tutorial",
            name="notificacion_creacion",
            field=models.ManyToManyField(
                related_name="notificacion_creacion_tutorial",
                through="api.NotificacionCreacionTutorial",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
