# Generated by Django 3.2.7 on 2021-11-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_notificacionplumacomentario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificacionplumacomentario",
            old_name="comunicado",
            new_name="comentario",
        ),
    ]
